### ISSUE TITLE
Interpolation issue with ES2015 syntax and bash

### ISSUE THREAD

**Issue by ghost** [zce/caz#146]
Hey there! 
First of all thank you for creating this tool. 

As I was implementing a scaffold tool for a React App I noticed the following issue, which from what I can see it is located in: https://github.com/zce/caz/blob/main/src/render.ts

```js
// With the code in https://github.com/zce/caz/blob/main/src/render.ts caz interpolates also valid Bash syntax and ES2015
// The problem is that it will throw an error for variables it tries to replace, but are not intended for interpolation and are just valid code. This is because lodash default behaviour is to try and replace also ${var} syntax.
result = _.template('${foo} something')({foo: 'bar'})
console.log(result) // prints bar something

// Fixing it would be something in the line of customising the interpolate setting to only work with <% %> wrapped variables.
const regexp = /<%=?([\s\S]+?)%>/
result = _.template('${foo} something escape', {interpolate: regexp})({foo: 'bar'})
console.log(result) // ${foo} something escape

// As you can see this is interpolated correctly, while valid ${var} is ignored. 
result = _.template('<%= foo %> something interpolated', {interpolate: regexp})({foo: 'bar'})
console.log(result) // bar something interpolated
```

This a related issue / question opened in lodash explaing further the solution proposed: https://github.com/lodash/lodash/issues/4039
I would be willing to contribute, but I first would like to hear your opinion, granted I did not test yet this code with helpers functions.

Have a nice day!

**Comment by zce** [comment]
@ettore-travelperk 
I have considered this plan before, but I gave it up later. 

Because many times we just need to output a simple variable in the template, such as the name of the project. In this case, the ES2015 syntax interpolation expression is very simple.

If you want to keep its output.

```javascript
result = _.template('<%= '${foo}' %> something')({foo: 'bar'})
console.log(result) // prints ${foo} something
```

Reference documents: https://github.com/zce/caz/blob/main/docs/create-template.md#template-paraphrase

**Comment by zce** [comment]
But you do remind me of another problem. When there is only ES2015 syntax interpolation expression in the template, it will not be processed at present

**Comment by ghost** [comment]
Gotcha, thanks for the docs!
