### ISSUE TITLE
Allow optional installation of template dependencies

### ISSUE THREAD

**Issue by ozeebee** [zce/caz#87]
Hello,

I know that, by design, you prefer to have [simple and lightweight](https://github.com/zce/caz/blob/main/docs/create-template.md#dependencies) templates. That's the reason why you "inherit" caz dependencies in the templates.

However, sometimes it may be desirable to allow the template to have its own dependencies.
I had the case where I just needed one additional library.
And I could not with the current implementation ;(

So, I [forked](https://github.com/ozeebee/caz) your project to add the possiblity to **optionally** install template dependencies.
This is done by passing an additional flag in the command-line.
If you don't pass it, it keeps the current behaviour.

Would you be interested in merging this feature into the codebase ?
I think this would be better than having separate "forks" with different features.
If so, let me know, and I will submit a PR.

In the meantime, you can test this feature with the fork.
I already have one [template](https://github.com/ozeebee/cdk-project-template) using this feature:

```bash
npx ozeebee/caz ozeebee/cdk-project-template [project-name] --tpldeps
```

Thanks !

**Comment by zce** [comment]
@ozeebee Thank you for your valuable advice. I'll consider it.

**Comment by zce** [comment]
@ozeebee Already on next tag

**Comment by findersky** [comment]
这是自动回信息！
 
    你好！首先感谢你的来信！如果不出意外最短在一个月内会得到我的回复，如果没有我的回复说明我还需要更多的时间！

**Comment by zce** [comment]
v1.0.0 released
